
<div class="janelaCadastroClientes p-3 mt-4 rounded">

  <section>
    <div class="d-flex justify-content-end">
        <a href="/home">    
          <button type="button" class="btn-close text-danger " aria-label="Close"></button>
        </a>
    </div>
    <div class="row justify-content-between" >
      <div class="col-md-6">
        <H1 class="fst-italic fs-1 text-light ">Cadastro de Clientes</H1>
      </div>
      <div class="col-md-6 mt-auto mb-auto d-flex justify-content-end ">
           <span>Data hora: <?=date('d/m/Y h:i A')?></span>
      </div>       
    </div> 


    
    <form method="post" action="#">
      <div class="row mt-4">
        <div class="col-md-4">
          <label for="nomeCliente" class="form-label"  >Nome Completo</label>
          <input type="text" class="form-control text-capitalize" id="nomeCliente" name="nome" required>
        </div>             
          
        <div class="col-md-4">
          <label for="cpf" class="form-label">CPF</label>
          <input type="" class="form-control" id="cpf" data-mask="000.000.000-00" name="cpf" placeholder="000.000.000-00" required>          
        </div>

        <div class="col-md-2">
          <label for="contato" class="form-label">Whats</label>
          <input type="tel" class="form-control" id="contato" name="contato"  data-mask="(49)90000-0000" placeholder="(xx)xxxxx-xxxx)" required >
        </div>
        <div class="col-md-2">
          <label for="contato" class="form-label">Tel fixo</label>
          <input type="tel" class="form-control" id="contato" name="contato"  data-mask="(49)0000-0000" placeholder="(xx)xxxx-xxxx)"  >
        </div>

        
        
       
      </div>
      <div class="row mt-4">
          <div class="col-md-5">
          <label for="enderecoCliente" class="form-label">Endereço</label>
          <input type="text" class="form-control" id="enderecoCliente" name="endereco"  required>
          </div>
          <div class="col-md-4">
          <label for="Complemento" class="form-label">Complemento</label>
          <input type="text" class="form-control" id="Complemento" name="complemento"   >
          </div>
          <div class="col-md-1">
          <label for="numero" class="form-label">N.Res</label>
          <input type="number" class="form-control" id="numero" name="numeroResidencia"   required>
          </div>
          <div class="col-md-2">
                <label for="Bairro" class="form-label" >Bairro</label>
                <select class="form-select" aria-label="Bairro" name="bairro">        
                  <option value="">Varzea</option>
                  <option value="" selected >Guarujá</option>
                  <option value="" >Centenario</option>
                  <option value="" >Santa Monica</option>
                  <option value="" >Centro</option>
                  <option value="" >Ponte Grande</option>
                  <option value="" >Habitação</option>
                  <option value="" >Dom Daniel</option>
                  <option value="">Tributo</option>
                  <option value="outros">Outros...</option>
                </select>
          </div>        
      </div>   
      
      <div class="row mt-4">
            <div class="col-md-4">
              <label for="inputZip" class="form-label">CEP</label>
              <input type="text" class="form-control" id="inputZip" name="cep" data-mask="00.000-000" placeholder="000.000-000">
            </div> 
        
            <div class="col-md-4">
              <label for="cidade" class="form-label">Cidade</label>
              <select class="form-select" aria-label="Default select example" name="cidade">        
                <option value="Blumenau">Blumenau</option>
                <option value="Gaspar" >Gaspar</option>
                <option value="lages" selected>Lages</option>
                <option value="Painel" >Painel</option>
                <option value="Ponte_Alta" >Ponte Alta</option>
                <option value="Urupema" >Urupema</option>
                <option value="São_Cristovão_do_Sul" >São Cristovão do Sul</option>
                <option value="São_Joaquim" >São Joaquim</option>
                <option value="São_José_do_Cerrito">São José do Cerrito</option>
                <option value="outros">Outros...</option>
              </select>
            </div>
            <div class="col-md-4 ">
              <label for="estados" class="form-label">Estado/Distrito</label>    
              <select id="estados" class="form-select " name="distrito">
              <option value="AC">Acre</option>
              <option value="AL">Alagoas</option>
              <option value="AP">Amapá</option>
              <option value="AM">Amazonas</option>
              <option value="BA">Bahia</option>
              <option value="CE">Ceará</option>
              <option value="DF">Distrito Federal</option>
              <option value="ES">Espírito Santo</option>
              <option value="GO">Goiás</option>
              <option value="MA">Maranhão</option>
              <option value="MT">Mato Grosso</option>
              <option value="MS">Mato Grosso do Sul</option>
              <option value="MG">Minas Gerais</option>
              <option value="PA">Pará</option>
              <option value="PB">Paraíba</option>
              <option value="PR">Paraná</option>
              <option value="PE">Pernambuco</option>
              <option value="PI">Piauí</option>
              <option value="RJ">Rio de Janeiro</option>
              <option value="RN">Rio Grande do Norte</option>
              <option value="RS">Rio Grande do Sul</option>
              <option value="RO">Rondônia</option>
              <option value="RR">Roraima</option>
              <option value="SC" selected>Santa Catarina</option>
              <option value="SP">São Paulo</option>
              <option value="SE">Sergipe</option>
              <option value="TO">Tocantins</option>
          
              
              </select>
            </div>
            
      </div>  
    
      <div class="col-md-12 mt-5">     
          <button  type="submit" class="btn btn-primary btn-lg">Cadastrar</button>  
      </div>
    </form> 
    
    </div>
  </section>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>