<div class="p-2   ">
  

  <section class="bg-success-subtle  p-3 m-3  ">
    <div class="d-flex justify-content-end ">
      <a href="/home">    
         <button type="button" class="btn-close " aria-label="Close"></button>
       </a>
  </div>
  <div >
    <H1 class="display-4 ">Cadastrar Clientes</H1>
  </div>
  <div >
   
    <form class="row g-4">
  <div class="col-md-4">
    <label for="nomeCliente" class="form-label">Nome Completo</label>
    <input type="text" class="form-control" id="nomeCliente" required>
  </div>
  <div class="col-md-4">
    <label for="cpfCliente" class="form-label">CPF</label>
    <input type="cpf" class="form-control" id="cpfCliente" required>
  </div>
  <div class="col-md-2">
    <label for="data" class="form-label">Data</label>
    <input type="Data" class="form-control" id="data" >
  </div>
  <div class="col-md-2">
    <label for="data" class="form-label">Hora</label>
    <input type="hora" class="form-control" id="hora" >
  </div>
  <div class="col-md-6">
    <label for="enderecoCliente" class="form-label">Endereço</label>
    <input type="text" class="form-control" id="enderecoCliente" placeholder="Endereço de Morada">
  </div>
  <div class="col-md-2">
    <label for="numero" class="form-label">N.Residência</label>
    <input type="text" class="form-control" id="numero">
  </div>
  <div class="col-md-2">
    <label for="Bairro" class="form-label">Bairro</label>
    <select class="form-select" aria-label="Bairro">        
      <option value="">Varzea</option>
      <option value="" selected >Guarujá</option>
      <option value="" >Centenario</option>
      <option value="" >Santa Monica</option>
      <option value="" >Centro</option>
      <option value="" >Ponte Grande</option>
      <option value="" >Habitação</option>
      <option value="" >Dom Daniel</option>
      <option value="">Tributo</option>
      <option value="outros">Outros...</option>
    </select>
  </div>
  <div class="col-md-2">
    <label for="inputZip" class="form-label">CEP</label>
    <input type="text" class="form-control" id="inputZip">
  </div>
 
  <div class="col-md-6">
    <label for="cidade" class="form-label">Cidade</label>
    <select class="form-select" aria-label="Default select example">        
      <option value="Blumenau">Blumenau</option>
      <option value="Gaspar" >Gaspar</option>
      <option value="lages" selected>Lages</option>
      <option value="Painel" >Painel</option>
      <option value="Ponte_Alta" >Ponte Alta</option>
      <option value="Urupema" >Urupema</option>
      <option value="São_Cristovão_do_Sul" >São Cristovão do Sul</option>
      <option value="São_Joaquim" >São Joaquim</option>
      <option value="São_José_do_Cerrito">São José do Cerrito</option>
      <option value="outros">Outros...</option>
    </select>
  </div>
  <div class="col-md-4 ">
    <label for="estados" class="form-label">Estado</label>    
    <select id="estados" class="form-select ">
    <option value="AC">Acre</option>
    <option value="AL">Alagoas</option>
    <option value="AP">Amapá</option>
    <option value="AM">Amazonas</option>
    <option value="BA">Bahia</option>
    <option value="CE">Ceará</option>
    <option value="DF">Distrito Federal</option>
    <option value="ES">Espírito Santo</option>
    <option value="GO">Goiás</option>
    <option value="MA">Maranhão</option>
    <option value="MT">Mato Grosso</option>
    <option value="MS">Mato Grosso do Sul</option>
    <option value="MG">Minas Gerais</option>
    <option value="PA">Pará</option>
    <option value="PB">Paraíba</option>
    <option value="PR">Paraná</option>
    <option value="PE">Pernambuco</option>
    <option value="PI">Piauí</option>
    <option value="RJ">Rio de Janeiro</option>
    <option value="RN">Rio Grande do Norte</option>
    <option value="RS">Rio Grande do Sul</option>
    <option value="RO">Rondônia</option>
    <option value="RR">Roraima</option>
    <option value="SC" selected>Santa Catarina</option>
    <option value="SP">São Paulo</option>
    <option value="SE">Sergipe</option>
    <option value="TO">Tocantins</option>
 
    
    </select>
  </div>
  
  
  <div class="col-12 mt-5 mb-5x">
    <button  type="submit" class="btn btn-primary ">Cadastrar</button>
  </div>
  </form> 
   
  </div>
  </section>




</div>