<?php
    session_start();
    $usuario= $_SESSION['usuario'];
    $usuario=strtoupper($usuario);


?>

  <div class="row" id="home" >,
    <aside class="col-md-2" id="lateral-esquerda">  
      <section class="mt-3 " id="area-logo">      
          <div class="d-flex justify-content-center" >
            <figure><img class="icon-usuario  " src="img/iconHome.png" alt=""></figure>  
          </div>  
          <div class="d-flex justify-content-center text-light" >
            <h5><?=$usuario ?></h5>         
          </div>
          <hr>           
      </section>
      
      <section class="p-3" id="area-funcoes-principais" >     
          <div class="btn-group  dropend mb-3 ms-2">
            <button type="button"  class="btn  dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="bi bi-person-fill-add text-light" ></i><span class="guias-laterais">Cadastrar</span> 
            </button>
            <ul class="dropdown-menu">                  
                <li  ><a id="cadastrarCliente" class="dropdown-item"  ><i class=" me-2 ms-1 fa-solid fa-user text-info"></i>Cliente</a></li>
                <li><a class="dropdown-item" href="#"><i class=" me-2 fa-solid fa-box-open text-info"></i>Produto</a></li>          
            </ul>          
          </div>

          <div class="btn-group dropend mb-2 ms-2">
            <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-zoom-in text-light"></i><span class="guias-laterais">Pesquisar</span> 
            </button>
            <ul class="dropdown-menu">                  
                <li><a class="dropdown-item" href="#"><i class=" me-2 ms-1 fa-solid fa-user text-info"></i>Cliente</a></li>
                <li><a class="dropdown-item" href="#"><i class=" me-2 fa-solid fa-box-open text-info"></i>Produto</a></li>          
            </ul>          
          </div>          
      </section>     

    </aside>    
    <main class="col-md" id="main" > 
      <div>

        <section class="row  mb-5">      
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Active</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
        </section> 
        
        <section class="row justify-content-evenly  mb-2"   >      
          <button type="button" class="mostradores col-md-2 btn btn-sm btn-primary  shadow" ><span>O.S Abertas</span><span class="ms-5" name="mostrador1">10</span></button>          
          <button type="button" class="mostradores col-md-2 btn btn-sm btn-success shadow"><span>O.S Andamento</span><span class="ms-5" name="mostrador2">1</span></button>          
          <button type="button" class="mostradores col-md-2 btn btn-sm btn-warning shadow"><span>O.S Pausadas</span><span class="ms-5" name="mostrador3">2</span></button>          
          <button type="button" class="mostradores col-md-2 btn btn-sm btn-secondary  shadow"><span>O.S Finalizadas</span><span class="ms-5" name="mostrador4">50</span></button>          
                  
        </section>  
      
        <section class="row" >
          <img class="img-main " src="/img/fundo_main.png" alt="">
          <div id="tela-principal" >
              
          </div>     
        </section>              
        <div class="footer ">
        <span class="me-1 text-dark">&copy;</span><small class="text-dark"> CopyRyght - Tech Need Informática</small>
        </div>
          
        
      </div> 

    </main> 
  </div>  
  


  



    
  